"""vLLM adapter for model inference.

This adapter implements the IModelInference port using vLLM's OpenAI-compatible API.
"""

from typing import Any

import httpx
from loguru import logger

from src.application.ports.ml_ports import IModelInference


class VLLMAdapter(IModelInference):
    """Adapter for vLLM model serving.

    This adapter communicates with a vLLM server through its OpenAI-compatible API.
    It handles both single-model and multi-model deployments.
    """

    def __init__(
        self,
        base_url: str,
        api_key: str | None = None,
        timeout: int = 60,
    ) -> None:
        """Initialize vLLM adapter.

        Args:
            base_url: Base URL of the vLLM server (e.g., "http://localhost:8000")
            api_key: Optional API key for authentication
            timeout: Request timeout in seconds
        """
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.timeout = timeout

        # Headers for requests
        self.headers = {"Content-Type": "application/json"}
        if api_key:
            self.headers["Authorization"] = f"Bearer {api_key}"

        logger.info(f"Initialized vLLM adapter with base URL: {base_url}")

    async def predict(
        self,
        model_id: str,
        input_data: dict[str, Any],
        parameters: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Run inference on a model.

        Args:
            model_id: Model identifier (model name in vLLM)
            input_data: Input data for prediction
            parameters: Optional inference parameters

        Returns:
            Prediction output
        """
        try:
            # Extract prompt from input_data
            prompt = input_data.get("prompt", input_data.get("text", ""))
            if not prompt:
                raise ValueError("Input must contain 'prompt' or 'text' field")

            # Prepare request parameters
            params = parameters or {}
            request_data = {
                "model": model_id,
                "prompt": prompt,
                "temperature": params.get("temperature", 0.7),
                "max_tokens": params.get("max_tokens", 512),
                "top_p": params.get("top_p", 0.9),
                "stream": False,
            }

            # Make request to vLLM completions endpoint
            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(
                    f"{self.base_url}/v1/completions",
                    json=request_data,
                    headers=self.headers,
                )
                response.raise_for_status()
                result = response.json()

            # Extract output from vLLM response
            if "choices" not in result or len(result["choices"]) == 0:
                raise ValueError("No output generated by model")

            choice = result["choices"][0]
            output_text = choice.get("text", "")

            # Prepare response
            output = {
                "text": output_text,
                "finish_reason": choice.get("finish_reason"),
                "usage": result.get("usage", {}),
            }

            # Add logprobs if available (can be used for confidence)
            if "logprobs" in choice and choice["logprobs"]:
                # Simple confidence estimation from logprobs
                # This is a rough estimation - adjust as needed
                logprobs = choice["logprobs"].get("token_logprobs", [])
                if logprobs:
                    avg_logprob = sum(logprobs) / len(logprobs)
                    # Convert log probability to probability (rough approximation)
                    confidence = min(1.0, max(0.0, (avg_logprob + 5) / 5))
                    output["confidence"] = confidence

            logger.debug(
                f"Generated {len(output_text)} characters "
                f"for model {model_id}"
            )

            return output

        except httpx.HTTPStatusError as e:
            logger.error(f"HTTP error during prediction: {e}")
            raise
        except Exception as e:
            logger.error(f"Prediction failed: {e}")
            raise

    async def predict_chat(
        self,
        model_id: str,
        messages: list[dict[str, str]],
        parameters: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Run chat inference on a model.

        Args:
            model_id: Model identifier
            messages: List of chat messages [{"role": "user", "content": "..."}]
            parameters: Optional inference parameters

        Returns:
            Chat completion output
        """
        try:
            params = parameters or {}
            request_data = {
                "model": model_id,
                "messages": messages,
                "temperature": params.get("temperature", 0.7),
                "max_tokens": params.get("max_tokens", 512),
                "top_p": params.get("top_p", 0.9),
                "stream": False,
            }

            async with httpx.AsyncClient(timeout=self.timeout) as client:
                response = await client.post(
                    f"{self.base_url}/v1/chat/completions",
                    json=request_data,
                    headers=self.headers,
                )
                response.raise_for_status()
                result = response.json()

            if "choices" not in result or len(result["choices"]) == 0:
                raise ValueError("No output generated by model")

            choice = result["choices"][0]
            message = choice.get("message", {})

            return {
                "role": message.get("role", "assistant"),
                "content": message.get("content", ""),
                "finish_reason": choice.get("finish_reason"),
                "usage": result.get("usage", {}),
            }

        except Exception as e:
            logger.error(f"Chat prediction failed: {e}")
            raise

    async def health_check(self, model_id: str) -> bool:
        """Check if a model is healthy and ready.

        Args:
            model_id: Model identifier

        Returns:
            True if healthy, False otherwise
        """
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                response = await client.get(
                    f"{self.base_url}/health",
                    headers=self.headers,
                )
                response.raise_for_status()
                return True
        except Exception as e:
            logger.warning(f"Health check failed for model {model_id}: {e}")
            return False

    async def get_model_info(self, model_id: str) -> dict[str, Any]:
        """Get information about a deployed model.

        Args:
            model_id: Model identifier

        Returns:
            Model information from vLLM
        """
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                # Get list of models from vLLM
                response = await client.get(
                    f"{self.base_url}/v1/models",
                    headers=self.headers,
                )
                response.raise_for_status()
                result = response.json()

                # Find the specific model
                models = result.get("data", [])
                for model in models:
                    if model.get("id") == model_id:
                        return model

                raise ValueError(f"Model {model_id} not found in vLLM server")

        except Exception as e:
            logger.error(f"Failed to get model info: {e}")
            raise

    async def list_models(self) -> list[dict[str, Any]]:
        """List all models available in vLLM.

        Returns:
            List of model information dictionaries
        """
        try:
            async with httpx.AsyncClient(timeout=10) as client:
                response = await client.get(
                    f"{self.base_url}/v1/models",
                    headers=self.headers,
                )
                response.raise_for_status()
                result = response.json()
                return result.get("data", [])

        except Exception as e:
            logger.error(f"Failed to list models: {e}")
            raise
