"""
TAJINEAgent - Strategic Meta-Agent for Territorial Intelligence

Implements the PERCEIVE-PLAN-DELEGATE-SYNTHESIZE-LEARN cycle
for high-level reasoning and task orchestration.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

from loguru import logger

from src.application.ports.agent_ports import AgentType
from src.infrastructure.agents.base_agent import BaseAgent
from src.infrastructure.agents.tajine.delegation import (
    bridge_relations_discover,
    create_manus_agent,
    execute_browser_action,
    fallback_delegate,
    run_data_hunt,
)
from src.infrastructure.agents.tajine.departments import (
    CITY_TO_DEPT_CAPITALIZED,
    DEPT_CODE_TO_NAME,
    SECTOR_CONCEPTS,
    SECTOR_TO_NAF,
    detect_sectors,
    extract_intent_fallback,
    extract_territory,
)
from src.infrastructure.agents.tajine.events import EventEmitter, TAJINECallback, TAJINEEvent
from src.infrastructure.agents.tajine.llm_router import (
    HybridLLMRouter,
    LLMRequest,
    TaskComplexity,
    create_hybrid_router,
)

if TYPE_CHECKING:
    from src.infrastructure.agents.manus import ManusAgent
    from src.infrastructure.agents.tajine.autonomy import AutonomyManager
    from src.infrastructure.agents.tajine.cognitive.engine import CognitiveEngine
    from src.infrastructure.agents.tajine.evaluator import Evaluator
    from src.infrastructure.agents.tajine.hunter import ResilientDataHunter
    from src.infrastructure.agents.tajine.learning import (
        DataCollector,
        TAJINEFineTuner,
        TerritorialExpertRouter,
    )

    # New cognitive enhancement components
    from src.infrastructure.agents.tajine.memory import EpisodicRetriever, EpisodicStore
    from src.infrastructure.agents.tajine.planning import StrategicPlanner
    from src.infrastructure.agents.tajine.reasoning import ChainOfThought, TreeOfThoughts

    # SAFLA integration
    from src.infrastructure.agents.tajine.safla import SAFLABridge
    from src.infrastructure.agents.tajine.semantic import SemanticSearchService
    from src.infrastructure.agents.tajine.trust import TrustManager
    from src.infrastructure.tools.registry import ToolRegistry


@dataclass
class Perception:
    """Result of perceive() - extracted intent and context."""

    intent: str
    territory: str | None = None
    sector: str | None = None
    horizon: str | None = None
    constraints: dict[str, Any] = field(default_factory=dict)


@dataclass
class SubTask:
    """A subtask to delegate to ManusAgent."""

    tool: str
    params: dict[str, Any]
    priority: int = 1
    timeout: int = 60
    required: bool = True


@dataclass
class ExecutionPlan:
    """Plan generated by plan() method."""

    subtasks: list[SubTask]
    strategy: str
    estimated_steps: int


@dataclass
class Synthesis:
    """Result of synthesize() - aggregated analysis."""

    analysis: dict[str, Any]
    confidence: float
    cognitive_levels: dict[str, Any]


class TAJINEAgent(BaseAgent, EventEmitter):
    """
    Strategic meta-agent with cognitive reasoning capabilities.

    Implements 4-layer architecture:
    - Strategic: TAJINEAgent (this class)
    - Tactical: ManusAgent (delegated execution)
    - Operational: Tools via ToolRegistry
    - Learning: Trust updates and feedback

    Cycle: PERCEIVE -> PLAN -> DELEGATE -> SYNTHESIZE -> LEARN

    Event Emission:
    - Inherits EventEmitter for real-time progress callbacks
    - Emits TAJINEEvent during each PPDSL phase
    - Supports both sync callbacks and async WebSocket handlers
    """

    def __init__(
        self,
        name: str = "tajine_agent",
        local_model: str = "qwen3.5:27b",
        powerful_model: str = "qwen3.5:27b",
        ollama_host: str = "http://localhost:11434",
        oumi_api_key: str | None = None,
        config: dict[str, Any] | None = None,
    ):
        """
        Initialize TAJINEAgent.

        Args:
            name: Unique name for this agent instance
            local_model: Fast local LLM for simple tasks (Ollama)
            powerful_model: Powerful LLM for complex reasoning (Ollama fallback)
            ollama_host: Ollama server URL
            oumi_api_key: Optional Oumi.ai API key for cloud models
            config: Optional configuration dict
        """
        BaseAgent.__init__(self, AgentType.CUSTOM, config or {})
        EventEmitter.__init__(self)

        self._name = name
        self.local_model = local_model
        self.powerful_model = powerful_model
        self.ollama_host = ollama_host
        self.oumi_api_key = oumi_api_key

        # Core components (lazy initialization)
        self._cognitive_engine: CognitiveEngine | None = None
        self._trust_manager: TrustManager | None = None
        self._planner: StrategicPlanner | None = None
        self._manus_agent: ManusAgent | None = None
        self._tool_registry: ToolRegistry | None = None
        self._llm_router: HybridLLMRouter | None = None
        # New core components
        self._data_hunter: ResilientDataHunter | None = None
        self._evaluator: Evaluator | None = None
        self._autonomy_manager: AutonomyManager | None = None
        # Learning components (persistence)
        self._data_collector: DataCollector | None = None
        self._fine_tuner: TAJINEFineTuner | None = None
        # Semantic search (vector store)
        self._semantic_service: SemanticSearchService | None = None
        # Cognitive enhancement components (Phase 5)
        self._episodic_store: EpisodicStore | None = None
        self._episodic_retriever: EpisodicRetriever | None = None
        self._expert_router: TerritorialExpertRouter | None = None
        self._chain_of_thought: ChainOfThought | None = None
        self._tree_of_thoughts: TreeOfThoughts | None = None
        # SAFLA integration (persistent memory + metacognition)
        self._safla_bridge: SAFLABridge | None = None

        # Crawler integration (data enrichment)
        self._crawler_scheduler = None

        # State
        self._initialized = False
        self._current_task_id: str | None = None
        self.session_id: str | None = None  # WebSocket session ID for browser screenshot streaming
        self._manus_creation_attempted = False  # Track if we tried to create ManusAgent
        self._finetune_task: asyncio.Task | None = None  # Track background finetune task

        logger.info(
            f"TAJINEAgent '{name}' initialized with models: {local_model}, {powerful_model}"
        )

    @property
    def name(self) -> str:
        """Get agent name."""
        return self._name

    @property
    def agent_type(self) -> str:
        """Get agent type - always 'tajine'."""
        return "tajine"

    @agent_type.setter
    def agent_type(self, value) -> None:
        """Allow BaseAgent to set this, but we always return 'tajine'."""
        pass  # Intentionally ignore - we always return "tajine"

    @property
    def cognitive_engine(self) -> CognitiveEngine:
        """Lazy-load CognitiveEngine with HybridLLMRouter.

        The CognitiveEngine uses the router to intelligently select
        models based on the cognitive level complexity:
        - Discovery/Causal: MODERATE → LOCAL/STANDARD
        - Scenario/Strategy: COMPLEX → POWERFUL
        - Theoretical: CRITICAL → MAXIMUM
        """
        if self._cognitive_engine is None:
            from src.infrastructure.agents.tajine.cognitive import CognitiveEngine

            self._cognitive_engine = CognitiveEngine(llm_router=self.llm_router)
        return self._cognitive_engine

    @property
    def trust_manager(self) -> TrustManager:
        """Lazy-load TrustManager with auto-persistence."""
        if self._trust_manager is None:
            from pathlib import Path

            from src.infrastructure.agents.tajine.trust import TrustManager

            trust_path = Path("data/tajine/trust.json")
            trust_path.parent.mkdir(parents=True, exist_ok=True)
            # Load existing state or create new
            if trust_path.exists():
                self._trust_manager = TrustManager.load_from_file(trust_path)
                if self._trust_manager is None:
                    self._trust_manager = TrustManager()
            else:
                self._trust_manager = TrustManager()
            # Enable auto-persist on every update
            self._trust_manager.enable_auto_persist(file_path=trust_path)
            logger.info(f"TrustManager initialized with auto-persist ({trust_path})")
        return self._trust_manager

    @property
    def llm_router(self) -> HybridLLMRouter:
        """Lazy-load HybridLLMRouter for intelligent model selection.

        Routes LLM requests based on:
        - Task complexity (SIMPLE → LOCAL, COMPLEX → POWERFUL)
        - Trust score from TrustManager
        - Confidence requirements

        Tiers:
        - LOCAL: Ollama (qwen2.5:7b) - fast, simple tasks
        - STANDARD: Oumi CoALM-8B - moderate reasoning
        - POWERFUL: Oumi CoALM-70B - complex analysis
        - MAXIMUM: Oumi CoALM-405B - critical decisions
        """
        if self._llm_router is None:
            self._llm_router = create_hybrid_router(
                local_model=self.local_model,
                ollama_host=self.ollama_host,
                oumi_api_key=self.oumi_api_key,
            )
            logger.info(f"HybridLLMRouter initialized with local={self.local_model}")
        return self._llm_router

    @property
    def planner(self) -> StrategicPlanner:
        """Lazy-load StrategicPlanner with tool registry and LLM client."""
        if self._planner is None:
            from src.infrastructure.agents.tajine.planning import StrategicPlanner

            # Try to create LLM client for intelligent decomposition
            llm_client = None
            try:
                from src.infrastructure.llm.ollama_client import OllamaClient

                llm_client = OllamaClient(
                    base_url="http://localhost:11434",
                    model=self.local_model,  # Use fast model for planning
                )
                logger.debug(f"StrategicPlanner using LLM: {self.local_model}")
            except Exception as e:
                logger.warning(f"LLM not available for planner: {e}")

            self._planner = StrategicPlanner(
                tool_registry=self.tool_registry,
                llm_client=llm_client,
                model=self.local_model,
                episodic_store=self.episodic_store,
            )
        return self._planner

    @property
    def tool_registry(self) -> ToolRegistry:
        """Lazy-load unified ToolRegistry with all agents as tools.

        Uses create_unified_registry() to get registry with:
        - Advanced agents: analyze_data, ml_pipeline, generate_code, etc.
        - CAMEL agents: territorial_data, territorial_geo, territorial_analyst
        - Browser/web tools: browser_action, crawl_web, deep_research
        """
        if self._tool_registry is None:
            from src.infrastructure.tools import create_unified_registry

            self._tool_registry = create_unified_registry(include_advanced=True, include_camel=True)
            logger.info(f"Created unified tool registry with {len(self._tool_registry)} tools")
        return self._tool_registry

    @property
    def data_hunter(self) -> ResilientDataHunter:
        """Lazy-load ResilientDataHunter for proactive data gathering.

        Includes semantic search capability via SemanticSearchService.
        Supports modes: normal, question, combler, rare, semantic, hybrid.
        """
        if self._data_hunter is None:
            from src.infrastructure.agents.tajine.hunter import (
                GraphExpander,
                HypothesisGenerator,
                ResilientDataHunter,
            )
            from src.infrastructure.agents.tajine.hunter.crawler import TAJINECrawler

            # Default sources for French territorial intelligence
            default_sources = [
                "sirene",
                "bodacc",
                "boamp",
                "insee",
                "data.gouv.fr",
                "openstreetmap",
                "web",
            ]
            self._data_hunter = ResilientDataHunter(
                sources=default_sources,
                hypothesis_generator=HypothesisGenerator(),
                graph_expander=GraphExpander(),
                crawler=TAJINECrawler(),
                semantic_service=self.semantic_service,  # NEW: Vector search
            )
            logger.info("ResilientDataHunter initialized with semantic search")
        return self._data_hunter

    @property
    def evaluator(self) -> Evaluator:
        """Lazy-load Evaluator for 3D data scoring.

        Uses blended coherence: 60% KG validation + 40% semantic coherence.
        """
        if self._evaluator is None:
            from src.infrastructure.agents.tajine.evaluator import (
                AlphaTester,
                Evaluator,
                KGValidator,
                SourceCredibilityScorer,
            )

            self._evaluator = Evaluator(
                source_scorer=SourceCredibilityScorer(),
                kg_validator=KGValidator(),
                alpha_tester=AlphaTester(),
                semantic_service=self.semantic_service,  # NEW: Semantic coherence
                use_semantic_coherence=True,  # Enable blended coherence
            )
            logger.info("Evaluator initialized with 3D scoring + semantic coherence")
        return self._evaluator

    @property
    def autonomy_manager(self) -> AutonomyManager:
        """Lazy-load AutonomyManager for adaptive autonomy decisions."""
        if self._autonomy_manager is None:
            from src.infrastructure.agents.tajine.autonomy import AutonomyManager

            self._autonomy_manager = AutonomyManager(
                trust_manager=self.trust_manager,
            )
            logger.info("AutonomyManager initialized")
        return self._autonomy_manager

    @property
    def data_collector(self) -> DataCollector:
        """Lazy-load DataCollector for training data persistence."""
        if self._data_collector is None:
            from pathlib import Path

            from src.infrastructure.agents.tajine.learning import DataCollector

            storage_path = Path("data/tajine/training_data.json")
            storage_path.parent.mkdir(parents=True, exist_ok=True)
            self._data_collector = DataCollector(
                storage_path=storage_path,
                min_examples_trigger=100,
                min_preferences_trigger=50,
            )
            logger.info(f"DataCollector initialized (storage={storage_path})")
        return self._data_collector

    @property
    def fine_tuner(self) -> TAJINEFineTuner:
        """Lazy-load TAJINEFineTuner for automated model improvement.

        Uses OumiAdapter for local fine-tuning with CoALM multi-agent support.
        Falls back to Ollama if Oumi is not available.
        """
        if self._fine_tuner is None:
            from pathlib import Path

            from src.infrastructure.agents.tajine.learning import (
                LLMJudgeCurator,
                TAJINEFineTuner,
            )
            from src.infrastructure.agents.tajine.learning.oumi_bridge import (
                OumiModelEvaluator,
                OumiTrainingBridge,
            )
            from src.infrastructure.learning.oumi_adapter import OumiAdapter

            # Create Oumi adapter (fallback to Ollama if not installed)
            oumi_adapter = OumiAdapter(
                oumi_path="/opt/oumi",
                fallback_to_ollama=True,
                ollama_url=self.ollama_host,
            )

            # Create bridge to adapt OumiAdapter to TrainingBackend protocol
            training_backend = OumiTrainingBridge(
                oumi_adapter=oumi_adapter,
                output_dir=Path("models/tajine"),
                territory_code=None,  # Set per-analysis if needed
            )

            # Create evaluator using Oumi (replaces mock evaluation)
            evaluator = OumiModelEvaluator(oumi_adapter)

            # Create curator for quality filtering (uses heuristics if no LLM provider)
            curator = LLMJudgeCurator()

            self._fine_tuner = TAJINEFineTuner(
                data_collector=self.data_collector,
                curator=curator,
                training_backend=training_backend,
                evaluator=evaluator,  # Now using real evaluator, not mock
                current_model=self.local_model,
                output_dir=Path("models/tajine"),
            )
            logger.info(
                f"TAJINEFineTuner initialized with OumiTrainingBridge "
                f"(fallback_to_ollama={oumi_adapter.fallback_to_ollama})"
            )
        return self._fine_tuner

    @property
    def semantic_service(self) -> SemanticSearchService:
        """Lazy-load SemanticSearchService for vector-based search.

        Uses pgvector as primary store with Qdrant as fallback.
        Embeddings generated via Ollama (nomic-embed-text).
        """
        if self._semantic_service is None:
            from src.infrastructure.agents.tajine.semantic import SemanticSearchService

            self._semantic_service = SemanticSearchService(
                ollama_url=self.ollama_host,
                embedding_model="nomic-embed-text",
            )
            logger.info("SemanticSearchService initialized (pgvector primary, Qdrant fallback)")
        return self._semantic_service

    @property
    def episodic_store(self) -> EpisodicStore:
        """Lazy-load EpisodicStore for persisting past analyses.

        Stores Episode objects with query, territory, sector, and cognitive levels.
        Used by episodic_retriever for context retrieval in PERCEIVE phase.
        """
        if self._episodic_store is None:
            from pathlib import Path

            from src.infrastructure.agents.tajine.memory import EpisodicStore

            storage_path = Path("data/tajine/episodic_memory")
            storage_path.mkdir(parents=True, exist_ok=True)
            self._episodic_store = EpisodicStore(storage_path=str(storage_path))
            logger.info(f"EpisodicStore initialized (path={storage_path})")
        return self._episodic_store

    @property
    def episodic_retriever(self) -> EpisodicRetriever:
        """Lazy-load EpisodicRetriever for semantic episode retrieval.

        Retrieves similar past analyses during PERCEIVE phase to enrich context.
        Uses territory, sector, and semantic matching.
        """
        if self._episodic_retriever is None:
            from src.infrastructure.agents.tajine.memory import EpisodicRetriever
            from src.infrastructure.agents.tajine.memory.retriever import OllamaEmbeddingProvider

            embedding_provider = OllamaEmbeddingProvider(base_url=self.ollama_host)
            self._episodic_retriever = EpisodicRetriever(
                store=self.episodic_store,
                embedding_provider=embedding_provider,
            )
            logger.info("EpisodicRetriever initialized with episodic store")
        return self._episodic_retriever

    @property
    def safla_bridge(self) -> SAFLABridge:
        """Lazy-load SAFLABridge for persistent memory and metacognition.

        Provides:
        - Persistent hybrid memory (survives sessions)
        - Metacognitive strategy selection
        - Self-learning from execution outcomes
        - Territory knowledge accumulation
        """
        if self._safla_bridge is None:
            from src.infrastructure.agents.tajine.safla import SAFLABridge

            self._safla_bridge = SAFLABridge()
            logger.info("SAFLABridge initialized for persistent memory + metacognition")
        return self._safla_bridge

    async def enrich_with_crawler(self, query: str, territory: str | None = None) -> list[dict]:
        """Enrich data by triggering relevant crawler sources.

        Args:
            query: User query to match sources
            territory: Optional department code for filtering

        Returns:
            List of recent crawl results relevant to the query
        """
        try:
            from src.application.services.crawler_scheduler import get_crawler_scheduler

            scheduler = get_crawler_scheduler()

            # Get recent results
            recent = scheduler.get_recent_results(limit=50)

            # Filter by territory if specified
            if territory:
                recent = [r for r in recent if territory in str(r.get("data", {}))]

            # If no recent data, trigger a crawl
            if not recent:
                results = await scheduler.crawl_now()
                recent = results if results else []

            logger.info(f"Crawler enrichment: {len(recent)} results for query")
            return recent

        except Exception as e:
            logger.warning(f"Crawler enrichment failed: {e}")
            return []

    @property
    def expert_router(self) -> TerritorialExpertRouter:
        """Lazy-load TerritorialExpertRouter for MoE-based domain routing.

        Routes queries to territorial experts based on detected keywords:
        - immobilier, emploi, entreprises, finances_locales, demographie, infrastructure
        Collects training examples per domain for future MixLoRA fine-tuning.
        """
        if self._expert_router is None:
            from src.infrastructure.agents.tajine.learning import get_expert_router

            self._expert_router = get_expert_router()
            logger.info("TerritorialExpertRouter initialized (6 experts, top_k=2)")
        return self._expert_router

    @property
    def chain_of_thought(self) -> ChainOfThought:
        """Lazy-load ChainOfThought for explicit step-by-step reasoning.

        Provides transparent reasoning chains for SYNTHESIZE phase.
        Each step has: observation, reasoning, evidence, confidence.
        """
        if self._chain_of_thought is None:
            from src.infrastructure.agents.tajine.reasoning import ChainOfThought

            self._chain_of_thought = ChainOfThought(
                llm_provider=None,  # Will use fallback reasoning
                max_steps=8,
            )
            logger.info("ChainOfThought initialized (max_steps=8)")
        return self._chain_of_thought

    @property
    def tree_of_thoughts(self) -> TreeOfThoughts:
        """Lazy-load TreeOfThoughts for multi-path exploration.

        Used for complex decisions in STRATEGY and THEORETICAL levels.
        Explores multiple reasoning paths using BFS/DFS/BEST_FIRST.
        """
        if self._tree_of_thoughts is None:
            from src.infrastructure.agents.tajine.reasoning import SearchStrategy, TreeOfThoughts

            self._tree_of_thoughts = TreeOfThoughts(
                llm_provider=None,  # Will use fallback reasoning
                breadth=3,
                max_depth=4,
                strategy=SearchStrategy.BEST_FIRST,
            )
            logger.info("TreeOfThoughts initialized (breadth=3, max_depth=4, strategy=BEST_FIRST)")
        return self._tree_of_thoughts

    async def initialize(self) -> None:
        """Initialize the agent and its resources."""
        logger.info(f"Initializing TAJINEAgent '{self._name}'")
        self._initialized = True
        logger.info(f"TAJINEAgent '{self._name}' initialized successfully")

    async def shutdown(self) -> None:
        """Shutdown the agent and release resources."""
        logger.info(f"Shutting down TAJINEAgent '{self._name}'")
        self._initialized = False
        logger.info(f"TAJINEAgent '{self._name}' shutdown complete")

    async def health_check(self) -> bool:
        """Check if the agent is operational."""
        return self._initialized

    def _generate_task_id(self) -> str:
        """Generate unique task ID."""
        import uuid

        return f"tajine-{uuid.uuid4().hex[:8]}"

    async def perceive(self, query: str) -> dict[str, Any]:
        """
        PERCEIVE: Analyze user query to extract intent and context.

        Enhanced with:
        1. Expert routing - detect relevant territorial domains
        2. Episodic memory - retrieve similar past analyses for context
        3. Structured intent extraction via LLM

        Args:
            query: User's natural language query

        Returns:
            Dict with intent, territory, sector, horizon, constraints,
            plus episodic_context and expert_routing
        """
        logger.debug(f"Perceiving query: {query[:100]}...")

        # 1. Route to territorial experts (MoE)
        try:
            routing_result = self.expert_router.route(query)
            expert_routing = {
                "activated_experts": [e.value for e in routing_result.activated_experts],
                "weights": {e.value: w for e, w in routing_result.expert_weights.items()},
                "detected_keywords": routing_result.detected_keywords,
                "confidence": routing_result.confidence,
            }
            logger.debug(f"Expert routing: {expert_routing['activated_experts']}")
        except Exception as e:
            logger.warning(f"Expert routing failed: {e}")
            expert_routing = {"activated_experts": ["entreprises"], "confidence": 0.5}

        # 2. Use LLM to extract structured intent
        perception = await self._extract_intent(query)
        territory = perception.get("territory")
        sector = perception.get("sector")

        # 3. Retrieve episodic context (similar past analyses)
        episodic_context = []
        try:
            similar_episodes = await self.episodic_retriever.retrieve_for_context(
                query=query, territory=territory, sector=sector, k=3
            )
            for result in similar_episodes:
                episodic_context.append(
                    {
                        "query": result.episode.query,
                        "territory": result.episode.territory,
                        "score": result.score,
                        "cognitive_levels": result.episode.cognitive_levels,
                    }
                )
            if episodic_context:
                logger.info(f"Retrieved {len(episodic_context)} similar episodes for context")
        except Exception as e:
            logger.warning(f"Episodic retrieval failed: {e}")

        # 4. Enrich perception with routing and episodic context
        perception["expert_routing"] = expert_routing
        perception["episodic_context"] = episodic_context
        perception["raw_query"] = query

        logger.info(
            f"Perceived intent: {perception.get('intent')} (experts: {expert_routing['activated_experts']})"
        )
        return perception

    async def plan(self, perception: dict[str, Any]) -> dict[str, Any]:
        """
        PLAN: Decompose task into executable subtasks.

        Args:
            perception: Output from perceive()

        Returns:
            Dict with subtasks list, strategy, estimated_steps
        """
        logger.debug(f"Planning for intent: {perception.get('intent')}")

        plan = await self.planner.create_plan(perception)

        logger.info(f"Created plan with {len(plan.get('subtasks', []))} subtasks")
        return plan

    async def delegate(
        self, subtask: dict[str, Any], context: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        """
        DELEGATE: Send subtask to ManusAgent for execution.

        Passes enriched context including perception and plan info
        to help ManusAgent make better decisions.

        Args:
            subtask: Subtask dict with tool, params, timeout
            context: Optional context from perceive/plan phases

        Returns:
            Execution result from ManusAgent or fallback result
        """
        tool_name = subtask.get("tool", "unknown")
        params = subtask.get("params", {})
        logger.debug(f"Delegating subtask: {tool_name} with params: {params}")

        try:
            # ALWAYS use direct execution for browser_action to ensure Agent Live streaming
            # ManusAgent's LLM may respond with text instead of calling the tool
            if tool_name == "browser_action":
                logger.info("Using direct browser_action execution for Agent Live streaming")
                return await self._fallback_delegate(subtask)

            # Lazy-load ManusAgent (reused across subtasks)
            if self._manus_agent is None:
                self._manus_agent = await self._create_manus_agent()

            if self._manus_agent is None:
                logger.warning("ManusAgent unavailable, using direct tool execution")
                return await self._fallback_delegate(subtask)

            # Build enriched task config with context
            task_config = {
                "prompt": self._format_subtask_prompt(subtask, context),
                "tools": [tool_name],
                "timeout": subtask.get("timeout", 60),
                "action_type": subtask.get("tool", "execute"),
                # Pass context for ManusAgent enrichment
                "context": context or {},
            }

            # Execute via ManusAgent's reasoning loop
            result = await self._manus_agent.execute_task(task_config)

            # Extract result details
            task_result = result.get("result", {})
            iterations = 1
            if isinstance(task_result, dict):
                iterations = task_result.get("iterations", 1)

            success = result.get("status") == "completed"
            logger.info(
                f"ManusAgent delegation: {tool_name} -> {'success' if success else 'failed'}"
            )

            return {
                "status": result.get("status", "completed"),
                "tool": tool_name,
                "result": task_result,
                "success": success,
                "metadata": {
                    "iterations": iterations,
                    "agent": "manus",
                    "tool_results": task_result.get("tool_results", [])
                    if isinstance(task_result, dict)
                    else [],
                },
            }

        except Exception as e:
            logger.error(f"Delegation failed for {tool_name}: {e}")
            # Try fallback on error
            return await self._fallback_delegate(subtask)

    async def _create_manus_agent(self) -> ManusAgent | None:
        """Delegate to delegation module."""
        return await create_manus_agent(self)

    async def _fallback_delegate(self, subtask: dict[str, Any]) -> dict[str, Any]:
        """Delegate to delegation module."""
        return await fallback_delegate(self, subtask)

    async def _execute_browser_action(self, subtask: dict[str, Any]) -> dict[str, Any]:
        """Delegate to delegation module."""
        return await execute_browser_action(self, subtask)

    async def _run_data_hunt(
        self, perception: dict[str, Any], mode: str = "normal", task_id: str | None = None
    ) -> dict[str, Any]:
        """Delegate to delegation module."""
        return await run_data_hunt(self, perception, mode, task_id)

    async def _bridge_relations_discover(
        self, department_code: str, task_id: str | None = None
    ) -> None:
        """Delegate to delegation module."""
        await bridge_relations_discover(self, department_code, task_id)

    async def synthesize(self, results: list[dict[str, Any]]) -> dict[str, Any]:
        """
        SYNTHESIZE: Aggregate results through CognitiveEngine (fast mode).

        Args:
            results: List of execution results from delegate()

        Returns:
            Synthesis with analysis, confidence, cognitive_levels
        """
        logger.debug(f"Synthesizing {len(results)} results")

        synthesis = await self.cognitive_engine.process(results)

        logger.info(f"Synthesis confidence: {synthesis.get('confidence', 0):.2f}")
        return synthesis

    async def synthesize_unified(
        self,
        results: list[dict[str, Any]],
        context: dict[str, Any] | None = None,
        tier_override: str | None = None,
    ) -> dict[str, Any]:
        """
        SYNTHESIZE (UNIFIED): Aggregate all 5 cognitive levels into structured response.

        This is the COMPLETE mode that fuses all cognitive levels into a
        coherent, structured response with executive summary and recommendations.

        Args:
            results: List of execution results from delegate()
            context: Optional context (territory, sector, query)
            tier_override: Force specific tier for LLM calls ("powerful" for COMPLETE mode)

        Returns:
            Dict with unified_synthesis, markdown, confidence
        """
        logger.debug(f"Unified synthesis for {len(results)} results, tier_override={tier_override}")

        # Use the unified synthesis method with tier override
        unified = await self.cognitive_engine.process_unified(
            results, context, tier_override=tier_override
        )

        logger.info(f"Unified synthesis confidence: {unified.overall_confidence:.2f}")

        return {
            "unified_synthesis": unified.to_dict(),
            "markdown": unified.to_markdown(),
            "confidence": unified.overall_confidence,
            "cognitive_signature": unified.cognitive_signature,
        }

    async def learn(self, outcome: dict[str, Any]) -> None:
        """
        LEARN: Update trust score and send feedback to learning pipeline.

        This phase completes the PPDSL cycle by:
        1. Updating trust scores (auto-persisted)
        2. Recording interaction for training data
        3. Storing episode in episodic memory
        4. Adding training examples to expert router
        5. Checking and triggering fine-tuning if thresholds met

        Args:
            outcome: Dict with success, user_feedback, metrics, interaction,
                     perception, synthesis (for episodic storage)
        """
        logger.debug(f"Learning from outcome: {outcome.get('success')}")

        # 1. Update trust based on outcome (auto-persisted via enable_auto_persist)
        if outcome.get("success"):
            self.trust_manager.record_success()
        else:
            self.trust_manager.record_failure()

        # Record user feedback if provided
        feedback = outcome.get("user_feedback")
        if feedback:
            self.trust_manager.record_feedback(feedback)

        trust_score = self.trust_manager.get_trust_score()
        logger.info(f"Trust score updated: {trust_score:.2f}")

        # 2. Record interaction for training data collection
        interaction = outcome.get("interaction")
        if interaction:
            try:
                await self.data_collector.record_interaction(interaction)
                logger.debug(f"Recorded interaction {interaction.id} for training")
            except Exception as e:
                # Don't fail the learn phase over storage issues
                logger.warning(f"Failed to record interaction for training: {e}")

        # 3. Store episode in episodic memory (new)
        perception = outcome.get("perception", {})
        synthesis = outcome.get("synthesis", {})
        if perception.get("raw_query"):
            try:
                from src.infrastructure.agents.tajine.memory import Episode

                episode = Episode(
                    query=perception.get("raw_query", ""),
                    territory=perception.get("territory", ""),
                    sector=perception.get("sector", ""),
                    analysis_result=synthesis,
                    cognitive_levels=synthesis.get("cognitive_levels", {}),
                    user_feedback=feedback,
                    confidence_score=synthesis.get("confidence", 0.5),
                    keywords=perception.get("expert_routing", {}).get("detected_keywords", []),
                )
                episode_id = self.episodic_store.add(episode)
                logger.debug(f"Stored episode {episode_id} in episodic memory")
            except Exception as e:
                logger.warning(f"Failed to store episode: {e}")

        # 4. Add training example to expert router (MoE learning)
        expert_routing = perception.get("expert_routing", {})
        if expert_routing.get("activated_experts") and synthesis:
            try:
                from src.infrastructure.agents.tajine.learning import ExpertDomain

                for expert_name in expert_routing.get("activated_experts", []):
                    domain = ExpertDomain(expert_name)
                    training_example = {
                        "query": perception.get("raw_query", ""),
                        "territory": perception.get("territory"),
                        "sector": perception.get("sector"),
                        "response_summary": synthesis.get("analysis", {}).get("summary", ""),
                        "success": outcome.get("success", False),
                        "confidence": synthesis.get("confidence", 0.5),
                    }
                    self.expert_router.add_training_example(domain, training_example)
                logger.debug(
                    f"Added training examples to {len(expert_routing['activated_experts'])} experts"
                )
            except Exception as e:
                logger.warning(f"Failed to add expert training example: {e}")

        # 5. Record trust score for fine-tuning trigger detection
        self.fine_tuner.record_trust(trust_score)
        if outcome.get("performance_score"):
            self.fine_tuner.record_performance(outcome["performance_score"])

        # 6. Check if fine-tuning should trigger
        trigger = await self.fine_tuner.check_trigger()
        if trigger:
            logger.info(f"Fine-tuning triggered: {trigger.value}")
            # Launch background task with proper tracking
            self._finetune_task = asyncio.create_task(
                self._background_finetune(trigger), name=f"finetune-{trigger.value}"
            )
            self._finetune_task.add_done_callback(self._handle_finetune_done)
            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.LEARN_COMPLETE,
                    task_id=self._current_task_id,
                    message=f"Fine-tuning triggered: {trigger.value}",
                    data={"fine_tuning_triggered": trigger.value},
                )
            )

        # 7. Check expert router for domain-specific retraining
        try:
            expert_training = await self.expert_router.check_and_trigger_training(
                fine_tuner=self.fine_tuner,
                min_examples=50,
            )
            if expert_training.get("triggered"):
                trained_domains = [d["domain"] for d in expert_training.get("domains_trained", [])]
                logger.info(f"Expert domains trained: {trained_domains}")
                self.emit(
                    TAJINECallback(
                        event=TAJINEEvent.LEARN_COMPLETE,
                        task_id=self._current_task_id,
                        message=f"Expert training completed: {', '.join(trained_domains)}",
                        data={"expert_training": expert_training},
                    )
                )
            elif expert_training.get("domains_pending"):
                pending = expert_training["domains_pending"]
                logger.debug(f"Expert domains pending: {list(pending.keys())}")
        except Exception as e:
            logger.warning(f"Expert router training check failed: {e}")

        # 8. Record in SAFLA for persistent memory and metacognitive learning
        try:
            if interaction and synthesis:
                from src.infrastructure.agents.tajine.safla.metacognitive_adapter import (
                    PerformanceMetrics,
                    StrategyType,
                )

                # Determine strategy used
                strategy = StrategyType.DEEP_ANALYSIS  # Default for TAJINE full cycle
                if perception.get("expert_routing", {}).get("confidence", 0) > 0.8:
                    strategy = StrategyType.COLLABORATIVE

                metrics = PerformanceMetrics(
                    task_id=interaction.id,
                    duration_ms=interaction.duration_ms,
                    success=outcome.get("success", False),
                    confidence=synthesis.get("confidence", 0.5),
                    data_sources_used=len(interaction.tools_used),
                    cache_hit=False,  # TAJINE always does fresh analysis
                    strategy_used=strategy,
                )
                await self.safla_bridge.metacognitive.record_performance(metrics)

                # Store task result in SAFLA memory
                await self.safla_bridge.memory.store_task_memory(
                    task_id=interaction.id,
                    query=perception.get("raw_query", ""),
                    result=synthesis,
                    territory=perception.get("territory"),
                    sector=perception.get("sector"),
                    success=outcome.get("success", False),
                )
                logger.debug(f"Recorded execution in SAFLA: {interaction.id}")
        except Exception as e:
            logger.debug(f"SAFLA recording skipped: {e}")

    async def _background_finetune(self, method) -> None:
        """Run fine-tuning in background without blocking."""
        try:
            result = await self.fine_tuner.run_finetune(method=method)
            logger.info(f"Background fine-tuning completed: {result.status}")
        except Exception as e:
            logger.error(f"Background fine-tuning failed: {e}")

    def _handle_finetune_done(self, task: asyncio.Task) -> None:
        """Callback for background finetune task completion."""
        try:
            exc = task.exception()
            if exc:
                logger.error(f"Finetune task {task.get_name()} raised: {exc}")
        except asyncio.CancelledError:
            logger.info(f"Finetune task {task.get_name()} was cancelled")
        except asyncio.InvalidStateError:
            pass  # Task not done yet, shouldn't happen in done callback

    async def execute_task(self, task_config: dict[str, Any]) -> dict[str, Any]:
        """
        Execute full PERCEIVE-PLAN-DELEGATE-SYNTHESIZE-LEARN cycle.

        Emits TAJINEEvent at each phase for real-time progress tracking.

        Args:
            task_config: Dict with:
                - prompt: User query
                - unified: If True, uses UnifiedSynthesizer for multi-level response
                - cognitive_depth: Depth of analysis (1-5)
                - max_iterations: Max iterations for planning
                - mode: "fast" or "complete" (affects model selection)
                - model_tier: Explicit tier hint ("local", "standard", "powerful", "maximum")

        Returns:
            Dict with status, result, confidence, metadata
            When unified=True, includes 'unified_synthesis' and 'markdown' fields
        """
        import time

        start_time = time.monotonic()
        task_id = self._create_task(task_config)
        self._current_task_id = task_id
        prompt = task_config.get("prompt", "")
        unified_mode = task_config.get("unified", False)

        # Extract mode and tier for model routing (FAST vs COMPLETE differentiation)
        analysis_mode = task_config.get("mode", "fast")
        model_tier_hint = task_config.get("model_tier")

        # Auto-derive tier from mode if not explicitly provided
        # This is the KEY differentiation between Fast and Complete modes
        if not model_tier_hint and analysis_mode.lower() == "complete":
            from src.infrastructure.agents.tajine.llm_router import get_model_for_mode

            _, tier = get_model_for_mode("complete")
            model_tier_hint = tier.value
            logger.info(f"[execute_task] Mode=complete, auto-derived tier={model_tier_hint}")
        elif model_tier_hint:
            logger.info(f"[execute_task] Mode={analysis_mode}, tier_hint={model_tier_hint}")
        else:
            logger.info(f"[execute_task] Mode={analysis_mode}, using LOCAL tier (default routing)")

        # Emit task started
        self.emit(
            TAJINECallback(
                event=TAJINEEvent.TASK_STARTED,
                task_id=task_id,
                message=f"Starting PPDSL cycle for: {prompt[:50]}...",
                data={"prompt": prompt},
            )
        )

        try:
            # 1. PERCEIVE
            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.PERCEIVE_START,
                    task_id=task_id,
                    phase="perceive",
                    progress=5,
                    message="Analyzing query intent and context",
                )
            )
            self.emit_thinking(task_id, "Extracting intent, territory, sector from query")

            perception = await self.perceive(prompt)

            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.PERCEIVE_COMPLETE,
                    task_id=task_id,
                    phase="perceive",
                    progress=15,
                    message=f"Identified intent: {perception.get('intent')}",
                    data=perception,
                )
            )

            # 2. PLAN
            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.PLAN_START,
                    task_id=task_id,
                    phase="plan",
                    progress=20,
                    message="Decomposing task into subtasks",
                )
            )
            self.emit_thinking(task_id, "Creating execution plan with tool assignments")

            plan = await self.plan(perception)
            subtasks = plan.get("subtasks", [])

            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.PLAN_COMPLETE,
                    task_id=task_id,
                    phase="plan",
                    progress=25,
                    message=f"Created plan with {len(subtasks)} subtasks",
                    data={"strategy": plan.get("strategy"), "subtask_count": len(subtasks)},
                )
            )

            # 3. DELEGATE
            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.DELEGATE_START,
                    task_id=task_id,
                    phase="delegate",
                    progress=30,
                    message=f"Executing {len(subtasks)} subtasks + DataHunter",
                )
            )

            results = []

            # 3.1 Run DataHunter FIRST to collect real data from APIs
            # Use "hybrid" mode for complete analysis (semantic + multi-strategy)
            # Use "normal" mode for fast analysis
            hunt_mode = "hybrid" if analysis_mode.lower() == "complete" else "normal"

            # Add original query to perception for DataHunter
            perception_with_query = {**perception, "query": prompt}

            self.emit_thinking(
                task_id,
                f"DataHunter: Collecting data from SIRENE, BODACC, INSEE... (mode={hunt_mode})",
            )

            hunt_result = await self._run_data_hunt(
                perception_with_query, mode=hunt_mode, task_id=task_id
            )

            # Add hunt result to results for cognitive engine
            results.append({"tool": "data_hunter", "result": hunt_result})

            # Update trust based on hunt success
            self.trust_manager.record_tool_outcome("data_hunter", hunt_result.get("success", False))

            logger.info(
                f"DataHunter phase complete: {hunt_result.get('data_count', 0)} items "
                f"from {hunt_result.get('sources_used', [])}"
            )

            # 3.2 Execute planned subtasks (browser, specific tools)
            for i, subtask in enumerate(subtasks):
                tool_name = subtask.get("tool", "unknown")
                progress = 30 + (50 * (i + 1) // max(len(subtasks), 1))

                # Emit tool execution event
                self.emit(
                    TAJINECallback(
                        event=TAJINEEvent.DELEGATE_TOOL,
                        task_id=task_id,
                        phase="delegate",
                        progress=progress,
                        message=f"Executing tool: {tool_name}",
                        data={"tool": tool_name, "params": subtask.get("params", {})},
                    )
                )

                # Pass perception context to delegate for enriched execution
                result = await self.delegate(subtask, context=perception)
                results.append({"tool": tool_name, "result": result})

                # Update trust for tool outcome
                self.trust_manager.record_tool_outcome(tool_name, result.get("success", False))

            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.DELEGATE_COMPLETE,
                    task_id=task_id,
                    phase="delegate",
                    progress=80,
                    message=f"Completed {len(results)} tool executions",
                    data={"results_count": len(results)},
                )
            )

            # 4. SYNTHESIZE
            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.SYNTHESIZE_START,
                    task_id=task_id,
                    phase="synthesize",
                    progress=82,
                    message="Aggregating results through cognitive engine",
                )
            )

            # Choose synthesis mode based on unified flag
            if unified_mode:
                self.emit_thinking(
                    task_id, "Processing through all 5 cognitive levels (unified mode)"
                )
                # Build context for unified synthesis
                synthesis_context = {
                    "territory": perception.get("territory"),
                    "sector": perception.get("sector"),
                    "query": prompt,
                }
                # Pass tier hint for COMPLETE mode (forces POWERFUL tier for all cognitive levels)
                synthesis = await self.synthesize_unified(
                    results,
                    synthesis_context,
                    tier_override=model_tier_hint,  # "powerful" for COMPLETE mode
                )
                cognitive_levels = synthesis.get("cognitive_signature", {})
            else:
                self.emit_thinking(task_id, "Processing through analytical layers")
                synthesis = await self.synthesize(results)
                cognitive_levels = synthesis.get("cognitive_levels", {})

            # Emit cognitive level progress
            for level_name in cognitive_levels:
                self.emit(
                    TAJINECallback(
                        event=TAJINEEvent.SYNTHESIZE_LEVEL,
                        task_id=task_id,
                        phase="synthesize",
                        progress=88,
                        message=f"Processed level: {level_name}",
                        data={"level": level_name},
                    )
                )

            # Prepare synthesis data for emission
            synthesis_data = {"confidence": synthesis.get("confidence", 0), "unified": unified_mode}
            if unified_mode:
                synthesis_data["unified_synthesis"] = synthesis.get("unified_synthesis")
            else:
                synthesis_data["analysis"] = synthesis.get("analysis")

            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.SYNTHESIZE_COMPLETE,
                    task_id=task_id,
                    phase="synthesize",
                    progress=92,
                    message=f"Synthesis complete (confidence: {synthesis.get('confidence', 0):.1%})",
                    data=synthesis_data,
                )
            )

            # 5. LEARN
            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.LEARN_START,
                    task_id=task_id,
                    phase="learn",
                    progress=95,
                    message="Updating trust metrics and recording interaction",
                )
            )

            # Build Interaction for training data
            from datetime import datetime

            from src.infrastructure.agents.tajine.learning import Interaction

            # Build response as structured dict (NOT stringified) for proper training data
            response_data = {
                "analysis": synthesis.get("analysis", {}),
                "confidence": synthesis.get("confidence", 0.5),
                "cognitive_levels": cognitive_levels,
                "territory": perception.get("territory"),
                "mode": analysis_mode,
            }
            interaction = Interaction(
                id=task_id,
                timestamp=datetime.now(),
                query=prompt,
                response=response_data,  # Dict, not str() - DataCollector needs structured data
                context={
                    "perception": perception,
                    "plan": {"strategy": plan.get("strategy"), "subtask_count": len(subtasks)},
                    "department": perception.get("territory"),
                    "cognitive_levels": cognitive_levels,
                },
                tools_used=[s.get("tool", "unknown") for s in subtasks],
                cognitive_level=len(cognitive_levels) if cognitive_levels else 1,
                success=True,
                duration_ms=(time.monotonic() - start_time) * 1000,
            )

            await self.learn(
                {
                    "success": True,
                    "metrics": synthesis.get("confidence", 0),
                    "interaction": interaction,
                    "performance_score": synthesis.get("confidence", 0.5),
                }
            )

            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.LEARN_COMPLETE,
                    task_id=task_id,
                    phase="learn",
                    progress=98,
                    message=f"Trust updated: {self.trust_manager.get_trust_score():.2f}",
                    data={"trust_score": self.trust_manager.get_trust_score()},
                )
            )

            # Task completed
            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.TASK_COMPLETED,
                    task_id=task_id,
                    progress=100,
                    message="PPDSL cycle complete",
                    data={"confidence": synthesis.get("confidence", 0)},
                )
            )

            # Build result based on synthesis mode
            result = {
                "status": "completed",
                "task_id": task_id,
                "confidence": synthesis.get("confidence"),
                "metadata": {
                    "perception": perception,
                    "plan": plan,
                    "subtask_count": len(subtasks),
                    "trust_score": self.trust_manager.get_trust_score(),
                    "unified": unified_mode,
                },
            }

            if unified_mode:
                # Include unified synthesis data
                result["result"] = {
                    "response": synthesis.get("markdown", ""),
                    "analysis": synthesis.get("unified_synthesis", {}),
                }
                result["unified_synthesis"] = synthesis.get("unified_synthesis")
                result["markdown"] = synthesis.get("markdown")
                result["cognitive_signature"] = synthesis.get("cognitive_signature")
            else:
                # Standard mode - return strategy analysis
                result["result"] = synthesis.get("analysis")
                result["cognitive_levels"] = synthesis.get("cognitive_levels")

            return result

        except Exception as e:
            logger.error(f"Task execution failed: {e}")

            # Emit failure event
            self.emit(
                TAJINECallback(
                    event=TAJINEEvent.TASK_FAILED,
                    task_id=task_id,
                    message="Task execution failed",
                    error=str(e),
                )
            )

            await self.learn({"success": False})
            return {"status": "failed", "task_id": task_id, "error": str(e)}

    async def fast_respond(self, query: str, cognitive_level: str = "analytical") -> str:
        """
        Fast response mode - direct LLM call without PPDSL cycle.

        Bypasses the full multi-agent orchestration for quick responses.
        Used when speed is more important than comprehensive analysis.

        Args:
            query: User query to respond to
            cognitive_level: One of reactive, analytical, strategic, prospective, theoretical

        Returns:
            LLM-generated response as a string
        """
        import httpx

        level_prompts = {
            "reactive": "Donne une reponse rapide et directe.",
            "analytical": "Analyse les donnees et statistiques pertinentes.",
            "strategic": "Propose des recommandations strategiques.",
            "prospective": "Fais des predictions basees sur les tendances.",
            "theoretical": "Applique les cadres theoriques economiques.",
        }

        level_instruction = level_prompts.get(cognitive_level, level_prompts["analytical"])

        system_prompt = f"""Tu es TAJINE (Territorial Agent for Joint Intelligence and Economic Navigation), expert en intelligence territoriale et economique francaise.

Tu analyses les DONNEES PUBLIQUES francaises suivantes:
- SIRENE: Registre des entreprises (creations, modifications, radiations/cessations d'activite)
- BODACC: Bulletin officiel des annonces civiles et commerciales (radiations, liquidations, creations)
- BOAMP: Marches publics
- INSEE: Statistiques demographiques et economiques
- BAN: Adresses georeferencees

IMPORTANT: Les "radiations" sont des CESSATIONS D'ACTIVITE d'entreprises - ce sont des donnees publiques legales publiees au BODACC. Tu DOIS les analyser quand demande.

{level_instruction}
Reponds en francais, de maniere structuree et professionnelle. Utilise les donnees reelles disponibles."""

        full_response = ""
        try:
            async with httpx.AsyncClient(timeout=60.0) as client:
                response = await client.post(
                    f"{self.ollama_host}/api/generate",
                    json={
                        "model": self.local_model,
                        "prompt": query,
                        "system": system_prompt,
                        "stream": False,
                    },
                )
                response.raise_for_status()
                data = response.json()
                full_response = data.get("response", "")

        except Exception as e:
            logger.error(f"Fast respond error: {e}")
            full_response = f"Erreur lors de la generation de la reponse: {str(e)}"

        return full_response

    async def _llm_generate(
        self,
        prompt: str,
        complexity: TaskComplexity = TaskComplexity.MODERATE,
        confidence_required: float = 0.7,
    ) -> str:
        """Generate LLM response using HybridLLMRouter.

        Args:
            prompt: The prompt to send to the LLM
            complexity: Task complexity for routing
            confidence_required: Minimum confidence requirement

        Returns:
            Generated text from the routed LLM
        """
        try:
            request = LLMRequest(
                prompt=prompt,
                complexity=complexity,
                trust_score=self.trust_manager.get_trust_score(),
                confidence_required=confidence_required,
            )

            response = await self.llm_router.route(request)
            logger.debug(
                f"LLM routed to {response.tier_used.value} (latency={response.latency_ms:.0f}ms)"
            )
            return response.content

        except Exception as e:
            logger.warning(f"LLM generation failed: {e}")
            return ""

    def _extract_territory_with_fallback(self, query: str) -> tuple[str | None, str | None]:
        """Delegate to departments module."""
        return extract_territory(query)

    async def _extract_intent(self, query: str) -> dict[str, Any]:
        """Extract structured intent from natural language query.

        Uses multi-level fallback chain for territory extraction:
        1. LLM-powered extraction (best quality)
        2. Department code regex (e.g., "69")
        3. Department name mapping (e.g., "Rhone" -> "69")
        4. City name mapping (e.g., "Lyon" -> "69")
        5. Default to "France" (never returns None)
        """
        import json
        import re

        detected_sectors, detected_naf_codes = detect_sectors(query)

        # Try LLM-powered extraction with enhanced prompt
        llm_prompt = f"""Extract the intent from this territorial intelligence query.
Respond in JSON format ONLY (no explanation):
{{
  "intent": "analyze|compare|prospect|monitor|search|explore_sectors",
  "territory": "department code (e.g. 69, 75) or 'France' for national",
  "territory_name": "department name (e.g. Rhone, Paris) or 'France'",
  "sector": "tech|sante|commerce|industrie|agriculture|services|energie|logistique|fintech|ia|multi_sector|null",
  "sector_concept": "secteurs_porteurs|croissance|innovation|economie_verte|null",
  "naf_codes": ["62.01Z", "..."] or null if not specific,
  "horizon": "court|moyen|long|null"
}}

IMPORTANT:
- If the query mentions "secteurs porteurs", "secteurs en croissance", "secteurs dynamiques", set sector_concept appropriately
- If multiple sectors are implied, use "multi_sector" and list relevant NAF codes
- "secteurs porteurs" typically means: tech (62.01Z, 62.02A), sante (86.10Z, 21.20Z), energies renouvelables (35.11Z)

Query: {query}"""

        try:
            response = await self._llm_generate(
                prompt=llm_prompt, complexity=TaskComplexity.SIMPLE, confidence_required=0.5
            )

            if response:
                json_match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", response)
                if json_match:
                    json_str = json_match.group(1)
                else:
                    json_match = re.search(r"\{[^{}]*\}", response, re.DOTALL)
                    json_str = json_match.group() if json_match else None

                if json_str:
                    extracted = json.loads(json_str)
                    extracted["raw_query"] = query

                    if detected_sectors:
                        extracted["detected_sectors"] = detected_sectors
                        extracted["naf_codes"] = list(set(detected_naf_codes))
                        if not extracted.get("sector") or extracted.get("sector") == "null":
                            extracted["sector"] = "multi_sector"
                        logger.debug(f"Enriched with conceptual sectors: {detected_sectors}")

                    for key in ["territory", "sector", "sector_concept", "horizon"]:
                        if extracted.get(key) in ("null", "None", "", None):
                            extracted[key] = None

                    territory = extracted.get("territory")
                    territory_name = extracted.get("territory_name")

                    if territory_name and territory_name not in ("null", "None", None):
                        city_dept = CITY_TO_DEPT_CAPITALIZED.get(territory_name)
                        if city_dept:
                            territory = city_dept
                            logger.debug(f"City mapping: {territory_name} -> {territory}")

                    if not territory and territory_name:
                        name_to_code = {v: k for k, v in DEPT_CODE_TO_NAME.items()}
                        territory = name_to_code.get(territory_name)

                    if territory:
                        extracted["territory"] = territory
                        if not extracted.get("territory_name"):
                            extracted["territory_name"] = DEPT_CODE_TO_NAME.get(
                                territory, territory
                            )
                    else:
                        code, name = extract_territory(query)
                        extracted["territory"] = code
                        extracted["territory_name"] = name

                    if not extracted.get("sector"):
                        query_lower = query.lower()
                        if any(
                            term in query_lower
                            for term in ["économique", "économie", "economic", "business"]
                        ):
                            extracted["sector"] = "multi_sector"

                    logger.debug(
                        f"LLM extracted intent: {extracted.get('intent')}, territory: {extracted.get('territory')}, sector: {extracted.get('sector')}"
                    )
                    return extracted
        except json.JSONDecodeError as e:
            logger.debug(f"LLM JSON parsing failed: {e}")
        except Exception as e:
            logger.debug(f"LLM extraction failed, using fallback: {e}")

        return extract_intent_fallback(query)

    def _format_subtask_prompt(
        self, subtask: dict[str, Any], context: dict[str, Any] | None = None
    ) -> str:
        """Format subtask into enriched prompt for ManusAgent.

        Includes context from perception/planning phases for better execution.

        Args:
            subtask: Subtask with tool and params
            context: Optional context from perception/plan

        Returns:
            Formatted prompt string with context
        """
        tool = subtask.get("tool", "unknown")
        params = subtask.get("params", {})

        # Build parameter string
        param_str = ", ".join(f"{k}={v}" for k, v in params.items())

        # Base prompt
        prompt = f"Execute the '{tool}' tool"
        if param_str:
            prompt += f" with parameters: {param_str}"

        # Add context if available
        if context:
            if intent := context.get("intent"):
                prompt = f"[Intent: {intent}] {prompt}"
            if territory := context.get("territory"):
                prompt += f" (territory: {territory})"
            if sector := context.get("sector"):
                prompt += f" (sector: {sector})"

        return prompt


def create_tajine_agent(
    name: str = "tajine_agent",
    local_model: str = "qwen2.5:7b",
    powerful_model: str = "qwen3-coder:30b",
    ollama_host: str = "http://localhost:11434",
    oumi_api_key: str | None = None,
    config: dict[str, Any] | None = None,
) -> TAJINEAgent:
    """
    Factory function to create configured TAJINEAgent.

    Args:
        name: Unique name for this agent instance
        local_model: Fast local LLM model name (Ollama)
        powerful_model: Powerful LLM model name (Ollama fallback)
        ollama_host: Ollama server URL
        oumi_api_key: Optional Oumi.ai API key for cloud models
        config: Optional configuration dict

    Returns:
        Configured TAJINEAgent instance with HybridLLMRouter
    """
    agent = TAJINEAgent(
        name=name,
        local_model=local_model,
        powerful_model=powerful_model,
        ollama_host=ollama_host,
        oumi_api_key=oumi_api_key,
        config=config,
    )

    logger.info("Created TAJINEAgent via factory with HybridLLMRouter support")
    return agent
